import Head from "next/head";
import Image from "next/image";
import Hero from "../../components/Hero/Hero";
import TrackProgress from "../../components/TrackProgress/TrackProgress";
import SetGoals from "../../components/SetGoals/SetGoals";
// import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Your Fitness Your Way</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main>
        <Hero />
        <div className="cards">
          <TrackProgress />
          <SetGoals />
        </div>
      </main>
    </div>
  );
}
