import Login from "../../components/Login/Login";
import Head from "next/head";
export default function LoginPage() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Login />
      </main>

    </div>
  );
}
