import SignUp from "../../components/SignUp/SignUp";
import Head from "next/head";
import Footer from "../../components/Footer/Footer";
export default function SignUpPage() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <SignUp />
      </main>
      <Footer />
    </div>
  );
}
